function B = Bmatrix(Ixx,Iyy,Izz,m)
%BMATRIX
%    B = BMATRIX(IXX,IYY,IZZ,M)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    16-Apr-2018 03:54:40

B = reshape([0.0,0.0,0.0,0.0,0.0,1.0./m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0./Ixx,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0./Iyy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0./Izz],[12,4]);
